plugins:
  # Name could be anything, this name is what appears on the beginning of operation
  # mappings.
  rest_plugin:
    executor: central_deployment_agent
    source: https://github.com/MichaelShn/cloudify-rest-plugin/archive/patch-1.zip
    package_name: cloudify-rest-plugin
    package_version: '0.0.1'

node_types:

  cloudify.rest.Requests:
    derived_from: cloudify.nodes.Root
    properties:
      hosts:
        description: >
          list of hosts name or IP addresses of Rest Servers
        default: []
      host:
        description: >
          host name or IP addresses of Rest Servers
          if list of hosts is not needed single host can be provided by this property.
          NOTE: the 'hosts' property overwirte the 'host' property
        default: []
      port:
        description: >
          port number. When -1 default ports are used (80 for ssl = false and 443 for ssl = true)
        type: integer
        default: -1
      ssl:
        description: >
          http or https
        type: boolean
        default: false
      verify:
        description: >
          A boolean which controls whether we verify
          the server's TLS certificate.
        type: boolean
        default: true

    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: rest_plugin.rest_plugin.tasks.execute
          inputs:
            params:
              default: {}
            template_file:
              default: ''
        configure:
          implementation: rest_plugin.rest_plugin.tasks.execute
          inputs:
            params:
              default: {}
            template_file:
              default: ''
        start:
          implementation: rest_plugin.rest_plugin.tasks.execute
          inputs:
            params:
              default: {}
            template_file:
              default: ''
        stop:
          implementation: rest_plugin.rest_plugin.tasks.execute
          inputs:
            params:
              default: {}
            template_file:
              default: ''
        delete:
          implementation: rest_plugin.rest_plugin.tasks.execute
          inputs:
            params:
              default: {}
            template_file:
              default: ''
